src/moviedb/home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'

urlpatterns = [
	url(r'^$', views.index, name='index'),
]

src/moviedb/login/urls.py
from django.conf.urls import url

from . import views

app_name = 'login'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^auth/', views.auth, name='auth'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^register/', views.register, name='register'),
]

src/moviedb/moviedb/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^login/', include('login.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^movies/', include('movies.urls')),
    url(r'^add_movie/', include('add_movie.urls')),
    url(r'^admin/', admin.site.urls),
]

src/moviedb/login/models.py
from django.db import models

class Username(models.Model):
    username_text = models.CharField(max_length=20)

    def __str__(self):
        return 'username'

class Password(models.Model):
    password_text = models.CharField(max_length=20)

    def __str__(self):
        return 'password'

src/moviedb/login/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from database.models import User, Status

manager_password = '123456789'

def index(request):
  return render(request, 'login/index.html')

# Checks if username and password are both correct
def auth(request):
  q_username = request.POST['username']
  q_password = request.POST['password']

  user = User.objects.all().filter(username=q_username)

  if user:

    if user[0].password == q_password:
      status = Status.objects.all()

      if status:
        status = status[0]
        status.logged_username = q_username
        status.save()

      else:
        status = Status(logged_username=q_username)
        status.save()

      return HttpResponseRedirect(reverse('home:index'))

    else:
      return render(request, 'login/index.html', {
          'auth_message': 'Wrong login',
      })

  else:
    return render(request, 'login/index.html', {
        'auth_message': 'Unknown user',
    })

# Checks to make sure the user is not registered already
def register(request):
  q_username = request.POST['username']
  q_password = request.POST['password']
  q_confirm = request.POST['password-confirm']

  if q_password != q_confirm:
    return render(request, 'login/index.html', {
        'register_message': 'Password confirm failed',
    })

  q_fname = request.POST['fname']
  q_mname = request.POST['mname']
  q_lname = request.POST['lname']
  q_dob = request.POST['dob']
  q_gender = request.POST['gender']
  q_manager = request.POST['password-manager'] == manager_password

  user = User.objects.all().filter(username=q_username)

  if user:
    return render(request, 'login/index.html', {
        'register_message': 'Existing user',
    })

  new_user = User(first_name=q_fname,
                  middle_name=q_mname,
                  last_name=q_lname,
                  username=q_username,
                  dob=q_dob,
                  gender=q_gender,
                  is_admin=q_manager,
                  password=q_password)
  new_user.save()

  if q_manager:
    return render(request, 'login/index.html', {
        'register_message': 'Registered manager user',
    })
  else:
    return render(request, 'login/index.html', {
        'register_message': 'Registered regular user',
    })

def logout(request):
  status = Status.objects.all()

  if status:
    status = status[0]
    status.logged_username = '' 
    status.save()

  else:
    status = Status(logged_username='')
    status.save()

  return HttpResponseRedirect(reverse('login:index'))

src/moviedb/login/templates/login/index.html
{% load static %}

<HTML>
  <title> MovieDB </title>
  <head>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'login-style.css' %}"/>
  </head>
  <body>
    <div class="fixed-header">
      <div class='fixed-header-title'> MovieDB </div>
    </div>

    <form class='login-form' action="{% url 'login:auth' %}" method="post"> 
      {% csrf_token %}
      <h1> Login </h1> <br>
      Username: <input type="text" name="username"> </input> <br>
      <br>
      Password: <input type="password" name="password"> </input> <br>
      <br>
      <input type='submit' value='Login'></input>

      {% if auth_message %} 
        <p><strong> {{ auth_message }} </strong></p>
      {% endif %}
    </form>

    <form class='register-form' action="{% url 'login:register' %}" method="post"> 
      {% csrf_token %}

      <h1> Register </h1> <br>
      Username: <input type="text" name="username"> </input> <br>
      <br>
      Password: <input type="password" name="password"> </input> <br>
      <br>
      Confirm:  <input type="password" name="password-confirm"> </input> <br>
      <br>
      First Name:  <input type="text" name="fname"> </input> <br>
      <br>
      Middle Initial:  <input type="text" name="mname"> </input> <br>
      <br>
      Last Name:  <input type="text" name="lname"> </input> <br>
      <br>
      DOB:  <input type="text" name="dob" placeholder="MM/DD/YYYY"> </input> <br>
      <br>
      Gender:  <select name="gender"> <option value="Male">Male</option> <option value="Female">Female</option> </select><br> 
      <br>
      Manager Password:  <input type="password" name="password-manager"> </input> <br>
      <br>
      <input type='submit' value='Register'></input>

      {% if register_message %} 
        <p><strong> {{ register_message }} </strong></p>
      {% endif %}
    </form>
  </body>
</HTML>