src/moviedb/add_movie/urls.py
from django.conf.urls import url

from . import views

app_name = 'add_movie'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^manage_movie/', views.manage_movie, name='manage_movie'),
	url(r'^upgrade_user/', views.upgrade_user, name='upgrade_user'),
]

src/moviedb/home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'

urlpatterns = [
	url(r'^$', views.index, name='index'),
]

src/moviedb/login/urls.py
from django.conf.urls import url

from . import views

app_name = 'login'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^auth/', views.auth, name='auth'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^register/', views.register, name='register'),
]

src/moviedb/moviedb/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^login/', include('login.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^movies/', include('movies.urls')),
    url(r'^add_movie/', include('add_movie.urls')),
    url(r'^admin/', admin.site.urls),
]

src/moviedb/movies/urls.py
from django.conf.urls import url

from . import views

app_name = 'movies'

urlpatterns = [
	url(r'^$', views.index, name='index'),
  url(r'^filters/$', views.filters, name='filters'),
	url(r'^(?P<mid>[0-9]+)/$', views.detail, name='detail'),
	url(r'^(?P<mid>[0-9]+)/add_review$', views.add_review, name='add_review'),
]

src/moviedb/movies/models.py
from django.db import models

# Create your models here.

src/moviedb/movies/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from database.models import *

def index(request):
  current_user = Status.objects.all()

  if not current_user:
    context = {
      'auth_message' : 'Please login first',
    }
    return render(request, 'login/index.html', context)

  current_user = current_user[0].logged_username

  if not current_user:
    context = {
      'auth_message' : 'Please login first',
    }
    return render(request, 'login/index.html', context)

  # Display who is logged in here
  movies = Movie.objects.all()

  container = []

  for movie in movies:
    instance = []
    instance.append(movie.mid)
    instance.append(movie.title)
    instance.append(movie.release)

    tags = Tags.objects.all().filter(mid=movie.mid)
    genres = Genres.objects.all().filter(mid=movie.mid)
    actors = Crew.objects.all().filter(mid=movie.mid, role='actor')
    
    tags   = ','.join([x.tags for x in tags])
    genres = ','.join([x.genres for x in genres])
    actors = ','.join([x.name for x in actors])

    instance.append(actors)
    instance.append(tags)
    instance.append(genres)

    container.append(instance)

  current_user = User.objects.all().filter(username=current_user)[0]

  context = {
    'movies' : container,
    'username' : 'Hello, %s %s' % (current_user.first_name, current_user.last_name),
    'is_admin' : current_user.is_admin,
  }

  return render(request, 'movies/index.html', context)

def filters(request):
  crew = request.POST['crew']
  title = request.POST['title']
  release = request.POST['release']
  tags = request.POST['tags']
  genre = request.POST['genre']

  movies = Movie.objects.all()

  if crew:
    crew = Crew.objects.all().filter(name=crew)
    mid = [x.mid for x in crew]
    movies = movies.filter(mid__in=mid)
  if title:
    movies = movies.filter(title=title)
  if release:
    movies = movies.filter(release=release)
  if tags:
    tags = Tags.objects.all().filter(tags=tags)
    mid = [x.mid for x in tags]
    movies = movies.filter(mid__in=mid)
  if genre:
    genre = Genres.objects.all().filter(genres=genre)
    mid = [x.mid for x in genre]
    movies = movies.filter(mid__in=mid)

  container = []

  for movie in movies:
    instance = []
    instance.append(movie.mid)
    instance.append(movie.title)
    instance.append(movie.release)

    tags = Tags.objects.all().filter(mid=movie.mid)
    genres = Genres.objects.all().filter(mid=movie.mid)
    actors = Crew.objects.all().filter(mid=movie.mid, role='actor')
    
    tags   = ','.join([x.tags for x in tags])
    genres = ','.join([x.genres for x in genres])
    actors = ','.join([x.name for x in actors])

    instance.append(actors)
    instance.append(tags)
    instance.append(genres)

    container.append(instance)

  current_user = Status.objects.all()
  current_user = current_user[0].logged_username
  current_user = User.objects.all().filter(username=current_user)[0]

  context = {
    'movies' : container,
    'username' : 'Hello, %s %s' % (current_user.first_name, current_user.last_name),
    'is_admin' : current_user.is_admin,
  }

  return render(request, 'movies/index.html', context)

def detail(request, mid):
  movie = Movie.objects.get(mid=mid)
  tags = Tags.objects.all().filter(mid=mid)
  genres = Genres.objects.all().filter(mid=mid)
  crew = Crew.objects.all().filter(mid=mid)

  tags = [x.tags for x in tags]
  genres = [x.genres for x in genres]
  crew = [x.name for x in crew]

  tags = ', '.join(tags)
  genres = ', '.join(genres)
  crew = ', '.join(crew)

  avg_rating = 0
  ratings = Rating.objects.all().filter(mid=mid)

  if ratings:
    for rating in ratings:
      avg_rating += rating.rating
    avg_rating /= len(ratings)

  movie_info = []
  movie_info.append(movie.title)
  movie_info.append(crew)
  movie_info.append(movie.release)
  movie_info.append(genres)
  movie_info.append(movie.duration)
  movie_info.append(movie.language)
  movie_info.append(tags)
  movie_info.append(movie.summary)
  movie_info.append(avg_rating)

  review_info = []
  reviews = Review.objects.all().filter(mid=mid)

  for review in reviews:
    review_text = review.review
    uid = review.uid
    username = User.objects.get(id=uid).username
    rating = Rating.objects.get(mid=mid, uid=uid).rating
    review_info.append([username, rating, review_text])

  current_user = Status.objects.all()
  current_user = current_user[0].logged_username
  current_user = User.objects.all().filter(username=current_user)[0]

  context = {
    'mid' : movie.mid,
    'movie_info' : movie_info,
    'review_info' : review_info,
    'username' : 'Hello, %s %s' % (current_user.first_name, current_user.last_name),
    'is_admin' : current_user.is_admin,
  }

  return render(request, 'movies/movie.html', context)

def add_review(request, mid):
  current_user = Status.objects.all()
  current_user = current_user[0].logged_username
  current_user = User.objects.all().filter(username=current_user)[0]

  if Rating.objects.filter(mid=mid, uid=current_user.id):
    return HttpResponseRedirect(reverse('movies:index'))

  rating = Rating(mid=mid, uid=current_user.id, rating=int(request.POST['rating']))
  review = Review(mid=mid, uid=current_user.id, review=request.POST['review_text'])
  rating.save()
  review.save()

  return HttpResponseRedirect(reverse('movies:index'))

src/moviedb/movies/templates/movies/index.html
{% load static %}

<HTML>
  <title> MovieDB </title>
  <head>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'movies-style.css' %}"/>
  </head>
  <body>
    <div class="fixed-header">
      <div class='fixed-header-title' onclick="location.href='{% url 'home:index' %}'"> MovieDB </div>
      <div class="fixed-header-login" onclick="location.href='{% url 'login:logout' %}'"> Logout </div>
      <div class="fixed-header-login"> {{ username }} </div>

      {% if is_admin %}
        <div class="fixed-header-add" onclick="location.href='{% url 'add_movie:index' %}'"> Manage </div>
      {% endif %}

      <div class="fixed-header-movies" onclick="location.href='{% url 'movies:index' %}'"> Movies </div>
    </div>


    <div class="fixed-sidebar">
      <form class="filters" action="{% url 'movies:filters' %}" method="post"> 
        {% csrf_token %}
        <h3>Filters</h3>
        Crew Member <br>
        <input type="text" name="crew"> </input> <br>
        <br>
        Title <br>
        <input type="text" name="title"> </input> <br>
        <br>
        Year <br>
        <input type="text" name="release"> </input> <br>
        <br>
        Tags <br>
        <input type="text" name="tags"> </input> <br>
        <br>
        Genre <br>
        <input type="text" name="genre"> </input> <br>
        <br>
        <input type='submit' value='Search!'></input>
      </form>

    </div>

    <div class='movies-container'>

    </div>

    <script>

function buildMovieCard(id, title, img, actors, year, genre, tags){
  var cardHTML = "<div class='movie-card'>";

  cardHTML += "<div class='movie-img-container'>";
  cardHTML +=	"<img class='movie-img' src='" + img +"'></img>";
  cardHTML += "</div>";

  cardHTML += "<div class='movie-text-top'>";
  cardHTML += "<a href=\"\/movies\/" + id + "\/\">" + "<span> Title: " + title + "</span></a><br>";
  cardHTML += "<span> Year: " + year + "</span><br>";
  cardHTML += "<span> Actors: " + actors + "</span><br>";
  cardHTML += "</div>";

  cardHTML += "<div class='movie-text-bottom'>";
  cardHTML += "<span> Tags: " + tags + "</span><br>";
  cardHTML += "<span> Genre(s): " + genre + "</span><br>";
  cardHTML += "</div>";

  cardHTML += "</div>";

  return cardHTML;

};

function appendMovieCard(img, id, title, year, actors, tags, genre){
  var cardHTML = buildMovieCard(id, title, img, actors, year, genre, tags);

  $('.movies-container').append(cardHTML);

};

{% for movie in movies %}
  var movie = {{ movie | safe }};
  appendMovieCard("{% static 'tortilla.jpg' %}", movie[0], movie[1], movie[2], movie[3], movie[4], movie[5]);
{% endfor %}

    </script>

  </body>
</HTML>

src/moviedb/movies/templates/movies/movie.html
{% load static %}

<HTML>
  <title> MovieDB </title>
  <head>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'movie-page-style.css' %}"/>
  </head>
  <body>
    <div class="fixed-header">
      <div class='fixed-header-title' onclick="location.href='{% url 'home:index' %}'"> MovieDB </div>
      <div class="fixed-header-login" onclick="location.href='{% url 'login:logout' %}'"> Logout </div>
      <div class="fixed-header-login"> {{ username }} </div>

      {% if is_admin %}
        <div class="fixed-header-add" onclick="location.href='{% url 'add_movie:index' %}'"> Manage </div>
      {% endif %}

      <div class="fixed-header-movies" onclick="location.href='{% url 'movies:index' %}'"> Movies </div>
    </div>
    <div class='review-container'>
      <div class='movie-container'>

      </div>

      <form class='add-review' action="{% url 'movies:add_review' mid %}" method="post">
        {% csrf_token %}
        <select name='rating'> 
          <option value='1'> 1 Star </option>
          <option value='2'> 2 Star </option>
          <option value='3'> 3 Star </option>
          <option value='4'> 4 Star </option>
          <option value='5'> 5 Star </option>
        </select>
        <textarea name='review_text' class='review' placeholder="Write your review here...."> </textarea>
        <input type="submit" value='Submit Review'>
      </form>

    </div>


    <div class='user-reviews'>

    </div>

    <script>

function buildMovieCard(title, img, actors, year, genre, duration, language, tags, description, avgRating){
  var cardHTML = "<div class='movie-card'>";

  cardHTML += "<div class='movie-img-container'>";
  cardHTML +=	"<img class='movie-img' src='" + img +"'></img>";
  cardHTML += "</div>";

  cardHTML += "<div class='movie-text-top'>";
  cardHTML += "<span> Title: " + title + "</span><br>";
  cardHTML += "<span> Release Date: " + year + "</span><br>";
  cardHTML += "<span> Film Crew: " + actors + "</span><br>";
  cardHTML += "<span> Duration: " + duration + "</span><br>";
  cardHTML += "<span> Language: " + language + "</span><br>";
  cardHTML += "<span> Tags: " + tags + "</span><br>";
  cardHTML += "<span> Genre(s): " + genre + "</span><br>";
  cardHTML += "<span> Average Rating: " + avgRating + "</span><br>";
  cardHTML += "</div>";

  cardHTML += "<div class='movie-text-bottom'>";

  cardHTML += "<span> Description: " + description + "</span><br>";

  cardHTML += "</div>";

  cardHTML += "</div>";

  return cardHTML;

};


function appendMovieCard(img, title, actors, year, genre, duration, language, tags, description, avgRating){
  var cardHTML = buildMovieCard(title, img, actors, year, genre, duration, language, tags, description, avgRating);

  $('.movie-container').append(cardHTML);

};

function buildReviewCard(username,rating, review){
  var cardHTML = "<div class='review-card'>";

  cardHTML += "<span>  " + username + " </span><br><br>";
  cardHTML += "<li>  Rated this film " + rating + "/5 </li><br><br>";
  cardHTML += "<span> " + review + "</span><br><br><br>";

  cardHTML += "</div>";

  return cardHTML;
};

function appendReviewCard(username, rating, review){
  var cardHTML = buildReviewCard(username, rating, review);

  $('.user-reviews').append(cardHTML);
}

var movie = {{ movie_info | safe }};
appendMovieCard("{% static 'tortilla.jpg' %}", movie[0], movie[1], movie[2], movie[3], movie[4], movie[5], movie[6], movie[7], movie[8]);

var reviews = {{ review_info | safe }};
for(var i = 0; i < reviews.length; i++) {
  appendReviewCard(reviews[i][0], reviews[i][1], reviews[i][2]);
}

    </script>

  </body>
</HTML>